{
	"version": 1559947758,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/chao-sheet0.png",
		"images/player-sheet0.png",
		"images/fim-sheet0.png",
		"images/chaomovel-sheet0.png",
		"images/fundofase1.png",
		"images/jogadorgrafico-sheet0.png",
		"images/jogadorgrafico-sheet1.png",
		"images/espinho-sheet0.png",
		"images/telamorte-sheet0.png",
		"images/btnrecomecar-sheet0.png",
		"images/telamenu-sheet0.png",
		"images/telavitoria-sheet0.png",
		"images/btnfase2-sheet0.png",
		"images/fundofase2.png",
		"images/chaofase2-sheet0.png",
		"images/inimigo-sheet0.png",
		"images/muroinimigo-sheet0.png",
		"images/fundofase3.png",
		"images/chaofase3-sheet0.png",
		"images/sprite-sheet0.png",
		"media/jump2.m4a",
		"media/jump2.ogg",
		"media/spawn.m4a",
		"media/spawn.ogg",
		"media/sommorte.ogg",
		"media/yoda fon (online-audio-converter.com).ogg",
		"media/renegade_jubilee (online-audio-converter.com).m4a",
		"media/renegade_jubilee (online-audio-converter.com).ogg",
		"media/fortress_europe (online-audio-converter.com).m4a",
		"media/fortress_europe (online-audio-converter.com).ogg",
		"media/clean_break (online-audio-converter.com)(1).m4a",
		"media/clean_break (online-audio-converter.com)(1).ogg",
		"media/operatic_3 - fase2.ogg",
		"media/synergy - fase3.ogg",
		"media/musicafim.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}